# -*- coding: utf-8 -*-
"""
/***************************************************************************
 routeplanning
                                 A QGIS plugin
 Calculating the best route between two chosen point in terrain conditions.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-28
        copyright            : (C) 2024 by Zsofia Sarközy
        email                : sarkozyzsofi@student.elte.hu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load routeplanning class from file routeplanning.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .routeplanning import routeplanning
    return routeplanning(iface)
